name: Direct Java Compile

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Чтение кода
      uses: actions/checkout@v4

    - name: Настройка Java 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Скачивание библиотек Minecraft 1.13.2
      run: |
        mkdir -p lib
        curl -s -o lib/minecraft.jar https://launcher.mojang.com/v1/objects/3737db93722a9e29ee815c40ae90a787383a8f46/client.jar

    - name: Компиляция мода
      run: |
        mkdir -p bin
        find . -type f -name "*.java" | xargs javac -cp "lib/*" -d bin
        
        # Копирование ресурсов
        find . -type d -name "resources" -exec cp -r {}/. bin/ \; 2>/dev/null || true
        
        cd bin && zip -r ../AnimeCreveyBolrMod-1.13.2.jar .

    - name: Сохранение готового .jar
      uses: actions/upload-artifact@v4
      with:
        name: Compiled-Mod-1.13.2
        path: AnimeCreveyBolrMod-1.13.2.jar
